---
title: Ελληνικός Σύλλογος Πατσγουωρκ - Hellenic Patchwork Guild
timezone: Europe/Athens
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: paplomatoudes@gmail.com
description: 'A club where quilters from allover Greece can discuss and create beautifull
  works of art!

'
baseurl: 
url: http://paplomatoudes.gr
facebook_url: https://www.facebook.com/groups/360278980834385/
markdown: kramdown
