---
title: Greek Quilting Club
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: paplomatoudes@gmail.com
description: 'A club where quilters from allover Greece can discuss and create beautifull
  works of art!

'
baseurl: ''
url: http://paplomatoudes.gr
facebook_url: https://www.facebook.com/groups/430185743779860
markdown: kramdown
